---
chapter: 
knit: "bookdown::render_book"
---

# Conclusion

This thesis develops a way of determining the presence of the forecast combination puzzle in a two-model pool. Empirical results suggest that when both constituent models have similar in-sample fit, the equally-weighted combination will either provide an equivalent or superior forecast accuracy to the optimally-weighted forecast combination for both point and density combinations. On the other hand, when the in-sample fit difference between two models is quite different, the presence of the puzzle is ambiguous.

Importantly, we derive the relationship between the optimal weight and elements in the proposed models under the mean squared error scheme when using point combinations. According to the closed-form expression of the estimated optimal weight, it is obvious that it is tightly related with the sample size, the sign and magnitude of parameters in the constituent models, the sample variances of regressors, and the correlation between regressors. It can also be shown that a big difference in the in-sample performance of proposed models will move the estimated optimal weight away from a half (the equal weight), especially in a large sample case. Additionally, the optimal weight also interacts with the true DGP in a broad sense, which determines the estimated coefficients in the constituent models.

Not surprisingly, these findings can be applied to density combinations under the log score scheme, where the estimated optimal weight is unlikely to have a closed-form expression. However, two constituent models have a symmetrical relationship when the population weight is equal to a half in the MSE case. It may not be the same case in the log score case based on some empirical evidence from the simulation.

Working in the two-model pools provides an opportunity of exploring a variety of situations in a short period of time. The next challenging step should naturally be to investigate the multiple forecasts combination. It is also necessary to relax some of the restrict model assumptions and increase the complexity of the model structure in the simulation study. Under the mild definition of the forecast combination puzzle, it is hard to determine the significance of the accuracy difference between optimally-weighted combination and equally-weighted combination, given that neither the testing or an arbitrary choice will work for all cases. We leave them all to future research.


