---
knit: "bookdown::render_book"
---

\appendix

# Appendix  

```{r, echo=FALSE, eval=FALSE}
citation("tidyverse")
citation("dplyr")
citation("fpp3")
version$version.string
```


The S&P500 index dataset has a total of 2519 ($T$) observations and is partitioned into two periods with a rough proportion. The in-sample period contains the first 60% of the data ($R = 1511$), which is used to estimate all unknown parameters, including the optimal weight. The remaining 40% ($P = 1008$) becomes the out-of-sample period to evaluate the forecast performance.  

The following predictive models are used to study the two-model pools: 

1. Model 1: ARIMA(1,1,1) model with an intercept of the natural logarithm of S&P 500 index. 
\begin{equation*}
log(y_t) = c + log(y_{t-1}) + \phi_1\big[log(y_{t-1})-log(y_{t-2})\big] + \epsilon_t + \theta_1\epsilon_{t-1}
\end{equation*}

2. Model 2: ETS(M,N,N) model of the S&P 500 index.
\begin{align*}
y_t &= \ell_{t-1} (1+\epsilon_t) \\
\ell_t &= \ell_{t-1} (1+\alpha \epsilon_t) \\
\end{align*}

3. Model 3: ETS(M,A,N) model of the S&P 500 index.
\begin{align*}
y_t &= (\ell_{t-1} + b_{t-1})(1+\epsilon_t) \\
\ell_t &= (\ell_{t-1} + b_{t-1}) (1+\alpha \epsilon_t) \\
b_t &= b_{t-1} + \beta (\ell_{t-1} + b_{t-1})\epsilon_t \\
\end{align*}

4. Model 4: A linear regression model of the S&P 500 index and ARIMA(1,0,0) errors. 
\begin{align*}
y_t &= \beta_0 + \beta_1 t + u_t \\
u_t &= \phi_1 u_{t-1} + \epsilon_t
\end{align*}

5. Model 5: A linear regression model of the natural logarithm of the S&P 500 index and ARIMA(1,0,0) errors. 
\begin{align*}
log(y_t) &= \beta_0 + \beta_1 t + u_t \\
u_t &= \phi_1 u_{t-1} + \epsilon_t
\end{align*}

The $\epsilon_t$ in each model is assumed to be independent and normally distributed with a zero mean and a constant variance.


Exact formulas and explanations of these models can be found in @fpp3. The formula of the conditional variance for the ETS models in this case is discussed in Chapter 6.3 of @HKOS08. All codes are performed in R Statistical Software (version 4.2.1 (2022-06-23)). The packages used are `tidyverse` [@tidy19], `dplyr` [@dplyr23], and `fpp3` [@fpp23].


The unknown parameters are estimated by maximizing the likelihood function using the in-sample period data. Once the estimated are obtained, they are held fixed for the density evaluation. For each model, we generate the predictive densities at every future time point of S&P 500 index ($h=1,2,...,P$) given that all past information is known. In order to make a comparison between models, the log of S&P 500 index will be evaluated by the log normal density function.


The log predictive score of each model is calculated and presented in Table \ref{tab:1}. If only one model can be chosen, the model with the highest score will be preferred, which is the ETS(M,A,N) model with a score of -5881.7970 in this case.


\vspace{0.3cm}


\begin{table}[htbp!]
\centering
\caption{Log score of each candidate model}
\begin{tabular}{l*{4}{c}}
\hline
     ARIMA(1,1,1) & ETS(M,N,N) & ETS(M,A,N) & LM (linear) & LM (log) \\
    \hline
     -5911.1974 & -5883.9697  & -5881.7970 & -7532.1464 & -5918.5230\\
    \hline
\end{tabular}
\label{tab:1}
\end{table}

The top 4 combinations and their log scores are collected in Table \ref{tab:3}.

\begin{table}[ht]
  \centering
  \caption{The top four density forecast combinations evaluated by the log predictive score function}
    \begin{tabular}{ll}
    \toprule
    Combination & Log predictive score \\
    \midrule
    ARIMA(1,1,1) and ETS(M,N,N) & -5839.3045 \\
    ARIMA(1,1,1) and ETS(M,A,N) & -5842.7634 \\
    ETS(M,N,N) and  LM (log) & -5858.6397 \\
    ETS(M,A,N) and  LM (log) & -5859.7980 \\
    \bottomrule
    \end{tabular}
  \label{tab:3}
\end{table}




